apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    application-crd-id: kubeflow-pipelines
    app: proxy-agent-runner
  name: proxy-agent-runner
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - '*'