// Copyright 2019 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by go-swagger; DO NOT EDIT.

package pipeline_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetVersionTemplateParams creates a new GetVersionTemplateParams object
// with the default values initialized.
func NewGetVersionTemplateParams() *GetVersionTemplateParams {
	var ()
	return &GetVersionTemplateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetVersionTemplateParamsWithTimeout creates a new GetVersionTemplateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetVersionTemplateParamsWithTimeout(timeout time.Duration) *GetVersionTemplateParams {
	var ()
	return &GetVersionTemplateParams{

		timeout: timeout,
	}
}

// NewGetVersionTemplateParamsWithContext creates a new GetVersionTemplateParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetVersionTemplateParamsWithContext(ctx context.Context) *GetVersionTemplateParams {
	var ()
	return &GetVersionTemplateParams{

		Context: ctx,
	}
}

// NewGetVersionTemplateParamsWithHTTPClient creates a new GetVersionTemplateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetVersionTemplateParamsWithHTTPClient(client *http.Client) *GetVersionTemplateParams {
	var ()
	return &GetVersionTemplateParams{
		HTTPClient: client,
	}
}

/*GetVersionTemplateParams contains all the parameters to send to the API endpoint
for the get version template operation typically these are written to a http.Request
*/
type GetVersionTemplateParams struct {

	/*PipelineID*/
	PipelineID string
	/*VersionID*/
	VersionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get version template params
func (o *GetVersionTemplateParams) WithTimeout(timeout time.Duration) *GetVersionTemplateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get version template params
func (o *GetVersionTemplateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get version template params
func (o *GetVersionTemplateParams) WithContext(ctx context.Context) *GetVersionTemplateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get version template params
func (o *GetVersionTemplateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get version template params
func (o *GetVersionTemplateParams) WithHTTPClient(client *http.Client) *GetVersionTemplateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get version template params
func (o *GetVersionTemplateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPipelineID adds the pipelineID to the get version template params
func (o *GetVersionTemplateParams) WithPipelineID(pipelineID string) *GetVersionTemplateParams {
	o.SetPipelineID(pipelineID)
	return o
}

// SetPipelineID adds the pipelineId to the get version template params
func (o *GetVersionTemplateParams) SetPipelineID(pipelineID string) {
	o.PipelineID = pipelineID
}

// WithVersionID adds the versionID to the get version template params
func (o *GetVersionTemplateParams) WithVersionID(versionID string) *GetVersionTemplateParams {
	o.SetVersionID(versionID)
	return o
}

// SetVersionID adds the versionId to the get version template params
func (o *GetVersionTemplateParams) SetVersionID(versionID string) {
	o.VersionID = versionID
}

// WriteToRequest writes these params to a swagger request
func (o *GetVersionTemplateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param pipeline_id
	if err := r.SetPathParam("pipeline_id", o.PipelineID); err != nil {
		return err
	}

	// path param version_id
	if err := r.SetPathParam("version_id", o.VersionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
