// Copyright 2019 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by go-swagger; DO NOT EDIT.

package pipeline_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	pipeline_model "github.com/kubeflow/pipelines/backend/api/go_http_client/pipeline_model"
)

// GetVersionTemplateReader is a Reader for the GetVersionTemplate structure.
type GetVersionTemplateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetVersionTemplateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetVersionTemplateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetVersionTemplateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetVersionTemplateOK creates a GetVersionTemplateOK with default headers values
func NewGetVersionTemplateOK() *GetVersionTemplateOK {
	return &GetVersionTemplateOK{}
}

/*GetVersionTemplateOK handles this case with default header values.

A successful response.
*/
type GetVersionTemplateOK struct {
	Payload *pipeline_model.APIGetTemplateResponse
}

func (o *GetVersionTemplateOK) Error() string {
	return fmt.Sprintf("[GET /apis/v1beta1/pipelines/{pipeline_id}/versions/{version_id}/templates][%d] getVersionTemplateOK  %+v", 200, o.Payload)
}

func (o *GetVersionTemplateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(pipeline_model.APIGetTemplateResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetVersionTemplateDefault creates a GetVersionTemplateDefault with default headers values
func NewGetVersionTemplateDefault(code int) *GetVersionTemplateDefault {
	return &GetVersionTemplateDefault{
		_statusCode: code,
	}
}

/*GetVersionTemplateDefault handles this case with default header values.

GetVersionTemplateDefault get version template default
*/
type GetVersionTemplateDefault struct {
	_statusCode int

	Payload *pipeline_model.APIStatus
}

// Code gets the status code for the get version template default response
func (o *GetVersionTemplateDefault) Code() int {
	return o._statusCode
}

func (o *GetVersionTemplateDefault) Error() string {
	return fmt.Sprintf("[GET /apis/v1beta1/pipelines/{pipeline_id}/versions/{version_id}/templates][%d] GetVersionTemplate default  %+v", o._statusCode, o.Payload)
}

func (o *GetVersionTemplateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(pipeline_model.APIStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
