// Copyright 2019 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: backend/api/pipeline.proto

package go_client // import "github.com/kubeflow/pipelines/backend/api/go_client"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Url struct {
	PipelineUrl          string   `protobuf:"bytes,1,opt,name=pipeline_url,json=pipelineUrl,proto3" json:"pipeline_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Url) Reset()         { *m = Url{} }
func (m *Url) String() string { return proto.CompactTextString(m) }
func (*Url) ProtoMessage()    {}
func (*Url) Descriptor() ([]byte, []int) {
	return fileDescriptor_pipeline_2cdb53848c7dde00, []int{0}
}
func (m *Url) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Url.Unmarshal(m, b)
}
func (m *Url) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Url.Marshal(b, m, deterministic)
}
func (dst *Url) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Url.Merge(dst, src)
}
func (m *Url) XXX_Size() int {
	return xxx_messageInfo_Url.Size(m)
}
func (m *Url) XXX_DiscardUnknown() {
	xxx_messageInfo_Url.DiscardUnknown(m)
}

var xxx_messageInfo_Url proto.InternalMessageInfo

func (m *Url) GetPipelineUrl() string {
	if m != nil {
		return m.PipelineUrl
	}
	return ""
}

type CreatePipelineRequest struct {
	Pipeline             *Pipeline `protobuf:"bytes,1,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreatePipelineRequest) Reset()         { *m = CreatePipelineRequest{} }
func (m *CreatePipelineRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePipelineRequest) ProtoMessage()    {}
func (*CreatePipelineRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_pipeline_2cdb53848c7dde00, []int{1}
}
func (m *CreatePipelineRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePipelineRequest.Unmarshal(m, b)
}
func (m *CreatePipelineRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePipelineRequest.Marshal(b, m, deterministic)
}
func (dst *CreatePipelineRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePipelineRequest.Merge(dst, src)
}
func (m *CreatePipelineRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePipelineRequest.Size(m)
}
func (m *CreatePipelineRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePipelineRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePipelineRequest proto.InternalMessageInfo

func (m *CreatePipelineRequest) GetPipeline() *Pipeline {
	if m != nil {
		return m.Pipeline
	}
	return nil
}

type GetPipelineRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPipelineRequest) Reset()         { *m = GetPipelineRequest{} }
func (m *GetPipelineRequest) String() string { return proto.CompactTextString(m) }
func (*GetPipelineRequest) ProtoMessage()    {}
func (*GetPipelineRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_pipeline_2cdb53848c7dde00, []int{2}
}
func (m *GetPipelineRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPipelineRequest.Unmarshal(m, b)
}
func (m *GetPipelineRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPipelineRequest.Marshal(b, m, deterministic)
}
func (dst *GetPipelineRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPipelineRequest.Merge(dst, src)
}
func (m *GetPipelineRequest) XXX_Size() int {
	return xxx_messageInfo_GetPipelineRequest.Size(m)
}
func (m *GetPipelineRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPipelineRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPipelineRequest proto.InternalMessageInfo

func (m *GetPipelineRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ListPipelinesRequest struct {
	PageToken            string   `protobuf:"bytes,1,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	PageSize             int32    `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	SortBy               string   `protobuf:"bytes,3,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	Filter               string   `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPipelinesRequest) Reset()         { *m = ListPipelinesRequest{} }
func (m *ListPipelinesRequest) String() string { return proto.CompactTextString(m) }
func (*ListPipelinesRequest) ProtoMessage()    {}
func (*ListPipelinesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_pipeline_2cdb53848c7dde00, []int{3}
}
func (m *ListPipelinesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPipelinesRequest.Unmarshal(m, b)
}
func (m *ListPipelinesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPipelinesRequest.Marshal(b, m, deterministic)
}
func (dst *ListPipelinesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPipelinesRequest.Merge(dst, src)
}
func (m *ListPipelinesRequest) XXX_Size() int {
	return xxx_messageInfo_ListPipelinesRequest.Size(m)
}
func (m *ListPipelinesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPipelinesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPipelinesRequest proto.InternalMessageInfo

func (m *ListPipelinesRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

func (m *ListPipelinesRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListPipelinesRequest) GetSortBy() string {
	if m != nil {
		return m.SortBy
	}
	return ""
}

func (m *ListPipelinesRequest) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

type ListPipelinesResponse struct {
	Pipelines            []*Pipeline `protobuf:"bytes,1,rep,name=pipelines,proto3" json:"pipelines,omitempty"`
	TotalSize            int32       `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	NextPageToken        string      `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListPipelinesResponse) Reset()         { *m = ListPipelinesResponse{} }
func (m *ListPipelinesResponse) String() string { return proto.CompactTextString(m) }
func (*ListPipelinesResponse) ProtoMessage()    {}
func (*ListPipelinesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_pipeline_2cdb53848c7dde00, []int{4}
}
func (m *ListPipelinesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPipelinesResponse.Unmarshal(m, b)
}
func (m *ListPipelinesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPipelinesResponse.Marshal(b, m, deterministic)
}
func (dst *ListPipelinesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPipelinesResponse.Merge(dst, src)
}
func (m *ListPipelinesResponse) XXX_Size() int {
	return xxx_messageInfo_ListPipelinesResponse.Size(m)
}
func (m *ListPipelinesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPipelinesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPipelinesResponse proto.InternalMessageInfo

func (m *ListPipelinesResponse) GetPipelines() []*Pipeline {
	if m != nil {
		return m.Pipelines
	}
	return nil
}

func (m *ListPipelinesResponse) GetTotalSize() int32 {
	if m != nil {
		return m.TotalSize
	}
	return 0
}

func (m *ListPipelinesResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

type DeletePipelineRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePipelineRequest) Reset()         { *m = DeletePipelineRequest{} }
func (m *DeletePipelineRequest) String() string { return proto.CompactTextString(m) }
func (*DeletePipelineRequest) ProtoMessage()    {}
func (*DeletePipelineRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_pipeline_2cdb53848c7dde00, []int{5}
}
func (m *DeletePipelineRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePipelineRequest.Unmarshal(m, b)
}
func (m *DeletePipelineRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePipelineRequest.Marshal(b, m, deterministic)
}
func (dst *DeletePipelineRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePipelineRequest.Merge(dst, src)
}
func (m *DeletePipelineRequest) XXX_Size() int {
	return xxx_messageInfo_DeletePipelineRequest.Size(m)
}
func (m *DeletePipelineRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePipelineRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePipelineRequest proto.InternalMessageInfo

func (m *DeletePipelineRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetTemplateRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTemplateRequest) Reset()         { *m = GetTemplateRequest{} }
func (m *GetTemplateRequest) String() string { return proto.CompactTextString(m) }
func (*GetTemplateRequest) ProtoMessage()    {}
func (*GetTemplateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_pipeline_2cdb53848c7dde00, []int{6}
}
func (m *GetTemplateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTemplateRequest.Unmarshal(m, b)
}
func (m *GetTemplateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTemplateRequest.Marshal(b, m, deterministic)
}
func (dst *GetTemplateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTemplateRequest.Merge(dst, src)
}
func (m *GetTemplateRequest) XXX_Size() int {
	return xxx_messageInfo_GetTemplateRequest.Size(m)
}
func (m *GetTemplateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTemplateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTemplateRequest proto.InternalMessageInfo

func (m *GetTemplateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetTemplateResponse struct {
	Template             string   `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTemplateResponse) Reset()         { *m = GetTemplateResponse{} }
func (m *GetTemplateResponse) String() string { return proto.CompactTextString(m) }
func (*GetTemplateResponse) ProtoMessage()    {}
func (*GetTemplateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_pipeline_2cdb53848c7dde00, []int{7}
}
func (m *GetTemplateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTemplateResponse.Unmarshal(m, b)
}
func (m *GetTemplateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTemplateResponse.Marshal(b, m, deterministic)
}
func (dst *GetTemplateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTemplateResponse.Merge(dst, src)
}
func (m *GetTemplateResponse) XXX_Size() int {
	return xxx_messageInfo_GetTemplateResponse.Size(m)
}
func (m *GetTemplateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTemplateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTemplateResponse proto.InternalMessageInfo

func (m *GetTemplateResponse) GetTemplate() string {
	if m != nil {
		return m.Template
	}
	return ""
}

type GetVersionTemplateRequest struct {
	PipelineId           string   `protobuf:"bytes,1,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	VersionId            string   `protobuf:"bytes,2,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVersionTemplateRequest) Reset()         { *m = GetVersionTemplateRequest{} }
func (m *GetVersionTemplateRequest) String() string { return proto.CompactTextString(m) }
func (*GetVersionTemplateRequest) ProtoMessage()    {}
func (*GetVersionTemplateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_pipeline_2cdb53848c7dde00, []int{8}
}
func (m *GetVersionTemplateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVersionTemplateRequest.Unmarshal(m, b)
}
func (m *GetVersionTemplateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVersionTemplateRequest.Marshal(b, m, deterministic)
}
func (dst *GetVersionTemplateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVersionTemplateRequest.Merge(dst, src)
}
func (m *GetVersionTemplateRequest) XXX_Size() int {
	return xxx_messageInfo_GetVersionTemplateRequest.Size(m)
}
func (m *GetVersionTemplateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVersionTemplateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetVersionTemplateRequest proto.InternalMessageInfo

func (m *GetVersionTemplateRequest) GetPipelineId() string {
	if m != nil {
		return m.PipelineId
	}
	return ""
}

func (m *GetVersionTemplateRequest) GetVersionId() string {
	if m != nil {
		return m.VersionId
	}
	return ""
}

type CreateVersionRequest struct {
	PipelineId           string   `protobuf:"bytes,1,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	Version              *Version `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateVersionRequest) Reset()         { *m = CreateVersionRequest{} }
func (m *CreateVersionRequest) String() string { return proto.CompactTextString(m) }
func (*CreateVersionRequest) ProtoMessage()    {}
func (*CreateVersionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_pipeline_2cdb53848c7dde00, []int{9}
}
func (m *CreateVersionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateVersionRequest.Unmarshal(m, b)
}
func (m *CreateVersionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateVersionRequest.Marshal(b, m, deterministic)
}
func (dst *CreateVersionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateVersionRequest.Merge(dst, src)
}
func (m *CreateVersionRequest) XXX_Size() int {
	return xxx_messageInfo_CreateVersionRequest.Size(m)
}
func (m *CreateVersionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateVersionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateVersionRequest proto.InternalMessageInfo

func (m *CreateVersionRequest) GetPipelineId() string {
	if m != nil {
		return m.PipelineId
	}
	return ""
}

func (m *CreateVersionRequest) GetVersion() *Version {
	if m != nil {
		return m.Version
	}
	return nil
}

type GetVersionRequest struct {
	PipelineId           string   `protobuf:"bytes,1,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	VersionId            string   `protobuf:"bytes,2,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVersionRequest) Reset()         { *m = GetVersionRequest{} }
func (m *GetVersionRequest) String() string { return proto.CompactTextString(m) }
func (*GetVersionRequest) ProtoMessage()    {}
func (*GetVersionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_pipeline_2cdb53848c7dde00, []int{10}
}
func (m *GetVersionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVersionRequest.Unmarshal(m, b)
}
func (m *GetVersionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVersionRequest.Marshal(b, m, deterministic)
}
func (dst *GetVersionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVersionRequest.Merge(dst, src)
}
func (m *GetVersionRequest) XXX_Size() int {
	return xxx_messageInfo_GetVersionRequest.Size(m)
}
func (m *GetVersionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVersionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetVersionRequest proto.InternalMessageInfo

func (m *GetVersionRequest) GetPipelineId() string {
	if m != nil {
		return m.PipelineId
	}
	return ""
}

func (m *GetVersionRequest) GetVersionId() string {
	if m != nil {
		return m.VersionId
	}
	return ""
}

type ListVersionsRequest struct {
	PipelineId           string   `protobuf:"bytes,1,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListVersionsRequest) Reset()         { *m = ListVersionsRequest{} }
func (m *ListVersionsRequest) String() string { return proto.CompactTextString(m) }
func (*ListVersionsRequest) ProtoMessage()    {}
func (*ListVersionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_pipeline_2cdb53848c7dde00, []int{11}
}
func (m *ListVersionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListVersionsRequest.Unmarshal(m, b)
}
func (m *ListVersionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListVersionsRequest.Marshal(b, m, deterministic)
}
func (dst *ListVersionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListVersionsRequest.Merge(dst, src)
}
func (m *ListVersionsRequest) XXX_Size() int {
	return xxx_messageInfo_ListVersionsRequest.Size(m)
}
func (m *ListVersionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListVersionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListVersionsRequest proto.InternalMessageInfo

func (m *ListVersionsRequest) GetPipelineId() string {
	if m != nil {
		return m.PipelineId
	}
	return ""
}

type ListVersionsResponse struct {
	Versions             []*Version `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListVersionsResponse) Reset()         { *m = ListVersionsResponse{} }
func (m *ListVersionsResponse) String() string { return proto.CompactTextString(m) }
func (*ListVersionsResponse) ProtoMessage()    {}
func (*ListVersionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_pipeline_2cdb53848c7dde00, []int{12}
}
func (m *ListVersionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListVersionsResponse.Unmarshal(m, b)
}
func (m *ListVersionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListVersionsResponse.Marshal(b, m, deterministic)
}
func (dst *ListVersionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListVersionsResponse.Merge(dst, src)
}
func (m *ListVersionsResponse) XXX_Size() int {
	return xxx_messageInfo_ListVersionsResponse.Size(m)
}
func (m *ListVersionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListVersionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListVersionsResponse proto.InternalMessageInfo

func (m *ListVersionsResponse) GetVersions() []*Version {
	if m != nil {
		return m.Versions
	}
	return nil
}

type Pipeline struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Name                 string               `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description          string               `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	DefaultVersion       *Version             `protobuf:"bytes,8,opt,name=default_version,json=defaultVersion,proto3" json:"default_version,omitempty"`
	Error                string               `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Pipeline) Reset()         { *m = Pipeline{} }
func (m *Pipeline) String() string { return proto.CompactTextString(m) }
func (*Pipeline) ProtoMessage()    {}
func (*Pipeline) Descriptor() ([]byte, []int) {
	return fileDescriptor_pipeline_2cdb53848c7dde00, []int{13}
}
func (m *Pipeline) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pipeline.Unmarshal(m, b)
}
func (m *Pipeline) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pipeline.Marshal(b, m, deterministic)
}
func (dst *Pipeline) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pipeline.Merge(dst, src)
}
func (m *Pipeline) XXX_Size() int {
	return xxx_messageInfo_Pipeline.Size(m)
}
func (m *Pipeline) XXX_DiscardUnknown() {
	xxx_messageInfo_Pipeline.DiscardUnknown(m)
}

var xxx_messageInfo_Pipeline proto.InternalMessageInfo

func (m *Pipeline) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Pipeline) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Pipeline) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Pipeline) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Pipeline) GetDefaultVersion() *Version {
	if m != nil {
		return m.DefaultVersion
	}
	return nil
}

func (m *Pipeline) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type Version struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Parameters           []*Parameter         `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty"`
	CodeSource           *CodeSource          `protobuf:"bytes,4,opt,name=code_source,json=codeSource,proto3" json:"code_source,omitempty"`
	Url                  *Url                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Version) Reset()         { *m = Version{} }
func (m *Version) String() string { return proto.CompactTextString(m) }
func (*Version) ProtoMessage()    {}
func (*Version) Descriptor() ([]byte, []int) {
	return fileDescriptor_pipeline_2cdb53848c7dde00, []int{14}
}
func (m *Version) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Version.Unmarshal(m, b)
}
func (m *Version) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Version.Marshal(b, m, deterministic)
}
func (dst *Version) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Version.Merge(dst, src)
}
func (m *Version) XXX_Size() int {
	return xxx_messageInfo_Version.Size(m)
}
func (m *Version) XXX_DiscardUnknown() {
	xxx_messageInfo_Version.DiscardUnknown(m)
}

var xxx_messageInfo_Version proto.InternalMessageInfo

func (m *Version) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Version) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Version) GetParameters() []*Parameter {
	if m != nil {
		return m.Parameters
	}
	return nil
}

func (m *Version) GetCodeSource() *CodeSource {
	if m != nil {
		return m.CodeSource
	}
	return nil
}

func (m *Version) GetUrl() *Url {
	if m != nil {
		return m.Url
	}
	return nil
}

type CodeSource struct {
	RepoName             string   `protobuf:"bytes,1,opt,name=repo_name,json=repoName,proto3" json:"repo_name,omitempty"`
	CommitSha            string   `protobuf:"bytes,2,opt,name=commit_sha,json=commitSha,proto3" json:"commit_sha,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CodeSource) Reset()         { *m = CodeSource{} }
func (m *CodeSource) String() string { return proto.CompactTextString(m) }
func (*CodeSource) ProtoMessage()    {}
func (*CodeSource) Descriptor() ([]byte, []int) {
	return fileDescriptor_pipeline_2cdb53848c7dde00, []int{15}
}
func (m *CodeSource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CodeSource.Unmarshal(m, b)
}
func (m *CodeSource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CodeSource.Marshal(b, m, deterministic)
}
func (dst *CodeSource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CodeSource.Merge(dst, src)
}
func (m *CodeSource) XXX_Size() int {
	return xxx_messageInfo_CodeSource.Size(m)
}
func (m *CodeSource) XXX_DiscardUnknown() {
	xxx_messageInfo_CodeSource.DiscardUnknown(m)
}

var xxx_messageInfo_CodeSource proto.InternalMessageInfo

func (m *CodeSource) GetRepoName() string {
	if m != nil {
		return m.RepoName
	}
	return ""
}

func (m *CodeSource) GetCommitSha() string {
	if m != nil {
		return m.CommitSha
	}
	return ""
}

func init() {
	proto.RegisterType((*Url)(nil), "api.Url")
	proto.RegisterType((*CreatePipelineRequest)(nil), "api.CreatePipelineRequest")
	proto.RegisterType((*GetPipelineRequest)(nil), "api.GetPipelineRequest")
	proto.RegisterType((*ListPipelinesRequest)(nil), "api.ListPipelinesRequest")
	proto.RegisterType((*ListPipelinesResponse)(nil), "api.ListPipelinesResponse")
	proto.RegisterType((*DeletePipelineRequest)(nil), "api.DeletePipelineRequest")
	proto.RegisterType((*GetTemplateRequest)(nil), "api.GetTemplateRequest")
	proto.RegisterType((*GetTemplateResponse)(nil), "api.GetTemplateResponse")
	proto.RegisterType((*GetVersionTemplateRequest)(nil), "api.GetVersionTemplateRequest")
	proto.RegisterType((*CreateVersionRequest)(nil), "api.CreateVersionRequest")
	proto.RegisterType((*GetVersionRequest)(nil), "api.GetVersionRequest")
	proto.RegisterType((*ListVersionsRequest)(nil), "api.ListVersionsRequest")
	proto.RegisterType((*ListVersionsResponse)(nil), "api.ListVersionsResponse")
	proto.RegisterType((*Pipeline)(nil), "api.Pipeline")
	proto.RegisterType((*Version)(nil), "api.Version")
	proto.RegisterType((*CodeSource)(nil), "api.CodeSource")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PipelineServiceClient is the client API for PipelineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PipelineServiceClient interface {
	CreatePipeline(ctx context.Context, in *CreatePipelineRequest, opts ...grpc.CallOption) (*Pipeline, error)
	GetPipeline(ctx context.Context, in *GetPipelineRequest, opts ...grpc.CallOption) (*Pipeline, error)
	ListPipelines(ctx context.Context, in *ListPipelinesRequest, opts ...grpc.CallOption) (*ListPipelinesResponse, error)
	DeletePipeline(ctx context.Context, in *DeletePipelineRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	GetTemplate(ctx context.Context, in *GetTemplateRequest, opts ...grpc.CallOption) (*GetTemplateResponse, error)
	CreateVersion(ctx context.Context, in *CreateVersionRequest, opts ...grpc.CallOption) (*Version, error)
	GetVersion(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*Version, error)
	ListVersions(ctx context.Context, in *ListVersionsRequest, opts ...grpc.CallOption) (*ListVersionsResponse, error)
	GetVersionTemplate(ctx context.Context, in *GetVersionTemplateRequest, opts ...grpc.CallOption) (*GetTemplateResponse, error)
}

type pipelineServiceClient struct {
	cc *grpc.ClientConn
}

func NewPipelineServiceClient(cc *grpc.ClientConn) PipelineServiceClient {
	return &pipelineServiceClient{cc}
}

func (c *pipelineServiceClient) CreatePipeline(ctx context.Context, in *CreatePipelineRequest, opts ...grpc.CallOption) (*Pipeline, error) {
	out := new(Pipeline)
	err := c.cc.Invoke(ctx, "/api.PipelineService/CreatePipeline", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pipelineServiceClient) GetPipeline(ctx context.Context, in *GetPipelineRequest, opts ...grpc.CallOption) (*Pipeline, error) {
	out := new(Pipeline)
	err := c.cc.Invoke(ctx, "/api.PipelineService/GetPipeline", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pipelineServiceClient) ListPipelines(ctx context.Context, in *ListPipelinesRequest, opts ...grpc.CallOption) (*ListPipelinesResponse, error) {
	out := new(ListPipelinesResponse)
	err := c.cc.Invoke(ctx, "/api.PipelineService/ListPipelines", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pipelineServiceClient) DeletePipeline(ctx context.Context, in *DeletePipelineRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/api.PipelineService/DeletePipeline", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pipelineServiceClient) GetTemplate(ctx context.Context, in *GetTemplateRequest, opts ...grpc.CallOption) (*GetTemplateResponse, error) {
	out := new(GetTemplateResponse)
	err := c.cc.Invoke(ctx, "/api.PipelineService/GetTemplate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pipelineServiceClient) CreateVersion(ctx context.Context, in *CreateVersionRequest, opts ...grpc.CallOption) (*Version, error) {
	out := new(Version)
	err := c.cc.Invoke(ctx, "/api.PipelineService/CreateVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pipelineServiceClient) GetVersion(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*Version, error) {
	out := new(Version)
	err := c.cc.Invoke(ctx, "/api.PipelineService/GetVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pipelineServiceClient) ListVersions(ctx context.Context, in *ListVersionsRequest, opts ...grpc.CallOption) (*ListVersionsResponse, error) {
	out := new(ListVersionsResponse)
	err := c.cc.Invoke(ctx, "/api.PipelineService/ListVersions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pipelineServiceClient) GetVersionTemplate(ctx context.Context, in *GetVersionTemplateRequest, opts ...grpc.CallOption) (*GetTemplateResponse, error) {
	out := new(GetTemplateResponse)
	err := c.cc.Invoke(ctx, "/api.PipelineService/GetVersionTemplate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PipelineServiceServer is the server API for PipelineService service.
type PipelineServiceServer interface {
	CreatePipeline(context.Context, *CreatePipelineRequest) (*Pipeline, error)
	GetPipeline(context.Context, *GetPipelineRequest) (*Pipeline, error)
	ListPipelines(context.Context, *ListPipelinesRequest) (*ListPipelinesResponse, error)
	DeletePipeline(context.Context, *DeletePipelineRequest) (*empty.Empty, error)
	GetTemplate(context.Context, *GetTemplateRequest) (*GetTemplateResponse, error)
	CreateVersion(context.Context, *CreateVersionRequest) (*Version, error)
	GetVersion(context.Context, *GetVersionRequest) (*Version, error)
	ListVersions(context.Context, *ListVersionsRequest) (*ListVersionsResponse, error)
	GetVersionTemplate(context.Context, *GetVersionTemplateRequest) (*GetTemplateResponse, error)
}

func RegisterPipelineServiceServer(s *grpc.Server, srv PipelineServiceServer) {
	s.RegisterService(&_PipelineService_serviceDesc, srv)
}

func _PipelineService_CreatePipeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePipelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PipelineServiceServer).CreatePipeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.PipelineService/CreatePipeline",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PipelineServiceServer).CreatePipeline(ctx, req.(*CreatePipelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PipelineService_GetPipeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPipelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PipelineServiceServer).GetPipeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.PipelineService/GetPipeline",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PipelineServiceServer).GetPipeline(ctx, req.(*GetPipelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PipelineService_ListPipelines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPipelinesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PipelineServiceServer).ListPipelines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.PipelineService/ListPipelines",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PipelineServiceServer).ListPipelines(ctx, req.(*ListPipelinesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PipelineService_DeletePipeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePipelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PipelineServiceServer).DeletePipeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.PipelineService/DeletePipeline",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PipelineServiceServer).DeletePipeline(ctx, req.(*DeletePipelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PipelineService_GetTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PipelineServiceServer).GetTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.PipelineService/GetTemplate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PipelineServiceServer).GetTemplate(ctx, req.(*GetTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PipelineService_CreateVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PipelineServiceServer).CreateVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.PipelineService/CreateVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PipelineServiceServer).CreateVersion(ctx, req.(*CreateVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PipelineService_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PipelineServiceServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.PipelineService/GetVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PipelineServiceServer).GetVersion(ctx, req.(*GetVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PipelineService_ListVersions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVersionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PipelineServiceServer).ListVersions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.PipelineService/ListVersions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PipelineServiceServer).ListVersions(ctx, req.(*ListVersionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PipelineService_GetVersionTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVersionTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PipelineServiceServer).GetVersionTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.PipelineService/GetVersionTemplate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PipelineServiceServer).GetVersionTemplate(ctx, req.(*GetVersionTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PipelineService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.PipelineService",
	HandlerType: (*PipelineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePipeline",
			Handler:    _PipelineService_CreatePipeline_Handler,
		},
		{
			MethodName: "GetPipeline",
			Handler:    _PipelineService_GetPipeline_Handler,
		},
		{
			MethodName: "ListPipelines",
			Handler:    _PipelineService_ListPipelines_Handler,
		},
		{
			MethodName: "DeletePipeline",
			Handler:    _PipelineService_DeletePipeline_Handler,
		},
		{
			MethodName: "GetTemplate",
			Handler:    _PipelineService_GetTemplate_Handler,
		},
		{
			MethodName: "CreateVersion",
			Handler:    _PipelineService_CreateVersion_Handler,
		},
		{
			MethodName: "GetVersion",
			Handler:    _PipelineService_GetVersion_Handler,
		},
		{
			MethodName: "ListVersions",
			Handler:    _PipelineService_ListVersions_Handler,
		},
		{
			MethodName: "GetVersionTemplate",
			Handler:    _PipelineService_GetVersionTemplate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backend/api/pipeline.proto",
}

func init() {
	proto.RegisterFile("backend/api/pipeline.proto", fileDescriptor_pipeline_2cdb53848c7dde00)
}

var fileDescriptor_pipeline_2cdb53848c7dde00 = []byte{
	// 1081 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0x5f, 0x6f, 0x1b, 0x45,
	0x10, 0xc7, 0x76, 0x93, 0xd8, 0xe3, 0x38, 0x51, 0x37, 0xff, 0x9c, 0x6b, 0xd2, 0x84, 0xa3, 0x0a,
	0x29, 0x50, 0xbb, 0x49, 0x45, 0xa5, 0x16, 0x21, 0x68, 0x42, 0x15, 0x2a, 0x51, 0x54, 0xd9, 0x09,
	0x0f, 0xed, 0xc3, 0x69, 0xed, 0x9b, 0x38, 0x4b, 0xce, 0xb7, 0xc7, 0xee, 0x3a, 0x21, 0x89, 0xf2,
	0x02, 0xe2, 0x89, 0x37, 0x78, 0xe6, 0x2b, 0xf0, 0x61, 0xe0, 0x85, 0x0f, 0xc0, 0x07, 0x41, 0xb7,
	0xb7, 0x7b, 0xb6, 0xcf, 0x4e, 0x94, 0x8a, 0x3e, 0xd9, 0x3b, 0xf3, 0xdb, 0x99, 0xf9, 0xcd, 0xce,
	0xfe, 0xf6, 0xc0, 0x69, 0xd1, 0xf6, 0x31, 0x86, 0x7e, 0x9d, 0x46, 0xac, 0x1e, 0xb1, 0x08, 0x03,
	0x16, 0x62, 0x2d, 0x12, 0x5c, 0x71, 0x52, 0xa0, 0x11, 0x73, 0x56, 0x3a, 0x9c, 0x77, 0x02, 0xd4,
	0x7e, 0x1a, 0x86, 0x5c, 0x51, 0xc5, 0x78, 0x28, 0x13, 0x88, 0xb3, 0x66, 0xbc, 0x7a, 0xd5, 0xea,
	0x1d, 0xd6, 0x15, 0xeb, 0xa2, 0x54, 0xb4, 0x1b, 0x19, 0xc0, 0x9d, 0x2c, 0x00, 0xbb, 0x91, 0x3a,
	0xb3, 0xce, 0xa1, 0xe4, 0x54, 0xd0, 0x2e, 0x2a, 0x14, 0xc6, 0xb9, 0x34, 0xe8, 0x44, 0x21, 0xb8,
	0x75, 0x7c, 0xa2, 0x7f, 0xda, 0x0f, 0x3a, 0x18, 0x3e, 0x90, 0xa7, 0xb4, 0xd3, 0x41, 0x51, 0xe7,
	0x91, 0xae, 0x6a, 0xb4, 0x42, 0x77, 0x13, 0x0a, 0x07, 0x22, 0x20, 0xef, 0xc3, 0xb4, 0x65, 0xe7,
	0xf5, 0x44, 0x50, 0xcd, 0xad, 0xe7, 0x36, 0x4b, 0x8d, 0xb2, 0xb5, 0x1d, 0x88, 0xc0, 0xdd, 0x81,
	0x85, 0x5d, 0x81, 0x54, 0xe1, 0x2b, 0x63, 0x6c, 0xe0, 0x0f, 0x3d, 0x94, 0x8a, 0xdc, 0x87, 0xa2,
	0xc5, 0xe9, 0x7d, 0xe5, 0xed, 0x4a, 0x8d, 0x46, 0xac, 0x96, 0xe2, 0x52, 0xb7, 0x7b, 0x0f, 0xc8,
	0x1e, 0xaa, 0x6c, 0x80, 0x19, 0xc8, 0x33, 0xdf, 0xa4, 0xcc, 0x33, 0xdf, 0xfd, 0x39, 0x07, 0xf3,
	0xdf, 0x30, 0x99, 0xe2, 0xa4, 0x05, 0xae, 0x02, 0x44, 0xb4, 0x83, 0x9e, 0xe2, 0xc7, 0x18, 0x9a,
	0x0d, 0xa5, 0xd8, 0xb2, 0x1f, 0x1b, 0xc8, 0x1d, 0xd0, 0x0b, 0x4f, 0xb2, 0x73, 0xac, 0xe6, 0xd7,
	0x73, 0x9b, 0x13, 0x8d, 0x62, 0x6c, 0x68, 0xb2, 0x73, 0x24, 0x4b, 0x30, 0x25, 0xb9, 0x50, 0x5e,
	0xeb, 0xac, 0x5a, 0xd0, 0x1b, 0x27, 0xe3, 0xe5, 0xce, 0x19, 0x59, 0x84, 0xc9, 0x43, 0x16, 0x28,
	0x14, 0xd5, 0x5b, 0x89, 0x3d, 0x59, 0xb9, 0xbf, 0xe6, 0x60, 0x21, 0x53, 0x85, 0x8c, 0x78, 0x28,
	0x91, 0x7c, 0x0c, 0x25, 0xcb, 0x48, 0x56, 0x73, 0xeb, 0x85, 0x51, 0xc6, 0x7d, 0x7f, 0x5c, 0xb3,
	0xe2, 0x8a, 0x06, 0x49, 0x55, 0x05, 0x5d, 0x55, 0x49, 0x5b, 0x74, 0x59, 0x1b, 0x30, 0x1b, 0xe2,
	0x8f, 0xca, 0x1b, 0xe0, 0x95, 0xd7, 0x65, 0x54, 0x62, 0xf3, 0x2b, 0xcb, 0xcd, 0xfd, 0x10, 0x16,
	0xbe, 0xc2, 0x00, 0x47, 0xbb, 0x9f, 0x6d, 0x5e, 0xd2, 0xe2, 0x7d, 0xec, 0x46, 0x01, 0x55, 0x57,
	0xa2, 0xb6, 0x60, 0x6e, 0x08, 0x65, 0x98, 0x39, 0x50, 0x54, 0xc6, 0x66, 0xc0, 0xe9, 0xda, 0x7d,
	0x03, 0xcb, 0x7b, 0xa8, 0xbe, 0x43, 0x21, 0x19, 0x0f, 0xb3, 0xf1, 0xd7, 0x20, 0x9d, 0x15, 0x2f,
	0x4d, 0x04, 0xd6, 0xf4, 0xc2, 0x8f, 0xdb, 0x70, 0x92, 0x6c, 0x8d, 0xfd, 0x09, 0xc5, 0x92, 0xb1,
	0xbc, 0xf0, 0x5d, 0x0f, 0xe6, 0x93, 0xe1, 0x32, 0xf1, 0x6f, 0x1c, 0x77, 0x03, 0xa6, 0x4c, 0x14,
	0x1d, 0xb4, 0xbc, 0x3d, 0xad, 0x4f, 0xc2, 0x86, 0xb1, 0x4e, 0xb7, 0x09, 0xb7, 0xfb, 0xd5, 0xbf,
	0xab, 0xaa, 0x1f, 0xc3, 0x5c, 0x3c, 0x21, 0x26, 0xaa, 0xbc, 0x69, 0x58, 0xf7, 0xcb, 0x64, 0xbe,
	0xfb, 0xfb, 0x4c, 0xfb, 0x37, 0xa1, 0x68, 0x82, 0xdb, 0xb9, 0x1a, 0x66, 0x93, 0x7a, 0xdd, 0x7f,
	0x72, 0x50, 0xb4, 0x93, 0x90, 0x3d, 0x5c, 0xf2, 0x04, 0xa0, 0xad, 0x9b, 0xe9, 0x7b, 0x54, 0x99,
	0xb6, 0x38, 0xb5, 0x44, 0x69, 0x6a, 0x56, 0x69, 0x6a, 0xfb, 0x56, 0x8a, 0x1a, 0x25, 0x83, 0x7e,
	0xa6, 0x08, 0x81, 0x5b, 0x21, 0xed, 0xa2, 0xb9, 0x22, 0xfa, 0x3f, 0x59, 0x87, 0xb2, 0x8f, 0xb2,
	0x2d, 0x98, 0x16, 0x11, 0x73, 0x4b, 0x06, 0x4d, 0xe4, 0x53, 0x98, 0xf5, 0xf1, 0x90, 0xf6, 0x02,
	0xe5, 0xd9, 0xc3, 0x28, 0x8e, 0x39, 0x8c, 0x19, 0x03, 0x32, 0x6b, 0x32, 0x0f, 0x13, 0x5a, 0xb8,
	0xaa, 0x93, 0x3a, 0x64, 0xb2, 0x70, 0xff, 0xca, 0xc1, 0x94, 0x45, 0xbc, 0x43, 0x66, 0xb5, 0x58,
	0x3b, 0x8c, 0x84, 0xca, 0x6a, 0x41, 0x77, 0x77, 0x26, 0xb9, 0xb5, 0xd6, 0xdc, 0x18, 0x40, 0x90,
	0x87, 0x50, 0x6e, 0x73, 0x1f, 0x3d, 0xc9, 0x7b, 0xa2, 0x8d, 0x9a, 0x75, 0x79, 0x7b, 0x56, 0x6f,
	0xd8, 0xe5, 0x3e, 0x36, 0xb5, 0xb9, 0x01, 0xed, 0xf4, 0x3f, 0x71, 0xa0, 0x10, 0x4b, 0xe7, 0x84,
	0x46, 0x16, 0x35, 0xf2, 0x40, 0x04, 0x8d, 0xd8, 0xe8, 0x7e, 0x0d, 0xd0, 0xdf, 0x15, 0x0b, 0x95,
	0xc0, 0x88, 0x7b, 0xba, 0xd5, 0xe6, 0x9e, 0xc5, 0x86, 0x6f, 0xe3, 0x76, 0xaf, 0x02, 0xb4, 0x79,
	0xb7, 0xcb, 0x94, 0x27, 0x8f, 0xa8, 0x9d, 0xb9, 0xc4, 0xd2, 0x3c, 0xa2, 0xdb, 0x7f, 0x16, 0x61,
	0xd6, 0x9e, 0x7c, 0x13, 0xc5, 0x09, 0x6b, 0x23, 0x39, 0x84, 0x99, 0x61, 0x69, 0x26, 0x4e, 0x52,
	0xe8, 0x38, 0xbd, 0x76, 0x86, 0xb5, 0xca, 0xbd, 0xff, 0xd3, 0xdf, 0xff, 0xfe, 0x9e, 0xff, 0xc0,
	0x5d, 0x8a, 0x5f, 0x12, 0x59, 0x3f, 0xd9, 0x6a, 0xa1, 0xa2, 0x5b, 0xe9, 0x63, 0x27, 0x9f, 0xa6,
	0xf2, 0x4d, 0xde, 0x40, 0x79, 0x40, 0xbe, 0xc9, 0x92, 0x0e, 0x34, 0x2a, 0xe8, 0xd9, 0x0c, 0xf7,
	0x74, 0x86, 0xbb, 0x64, 0xe5, 0x8a, 0x0c, 0xf5, 0x0b, 0xe6, 0x5f, 0x92, 0x0e, 0x54, 0x86, 0xe4,
	0x96, 0x2c, 0xeb, 0x28, 0xe3, 0x1e, 0x02, 0xc7, 0x19, 0xe7, 0x4a, 0x2e, 0x91, 0xbb, 0xa6, 0xb3,
	0x2d, 0x93, 0xab, 0xf8, 0x90, 0xef, 0x61, 0x66, 0x58, 0x4a, 0x4d, 0xb7, 0xc6, 0xea, 0xab, 0xb3,
	0x38, 0x32, 0x5e, 0xcf, 0xe3, 0x27, 0xda, 0x92, 0xfa, 0xe8, 0x7a, 0x52, 0x91, 0xee, 0x98, 0x55,
	0xcb, 0x7e, 0xc7, 0x32, 0xfa, 0xe9, 0x54, 0x47, 0x1d, 0x86, 0x4e, 0x4d, 0xe7, 0xd9, 0x24, 0x1b,
	0xd7, 0xe5, 0xa9, 0x5b, 0x95, 0x96, 0xe4, 0x0c, 0x2a, 0x43, 0x4a, 0x6a, 0xda, 0x38, 0x4e, 0x5d,
	0x9d, 0xa1, 0xeb, 0xe9, 0x7e, 0xa1, 0x33, 0x3d, 0x71, 0x6b, 0x57, 0x66, 0x1a, 0x50, 0xb5, 0xcb,
	0xba, 0xd5, 0xa2, 0xa7, 0x56, 0x63, 0xc9, 0x29, 0x40, 0x5f, 0x63, 0xc9, 0xa2, 0xa5, 0x74, 0x6d,
	0xd2, 0x5d, 0x9d, 0xf4, 0x73, 0xf2, 0xd9, 0xdb, 0x25, 0xad, 0x5f, 0xf4, 0x75, 0xf9, 0x92, 0x5c,
	0xc0, 0xf4, 0xa0, 0x9e, 0x92, 0x6a, 0x3a, 0x1e, 0x19, 0x69, 0x76, 0x96, 0xc7, 0x78, 0x4c, 0xa3,
	0x1f, 0xeb, 0x4a, 0x1e, 0x92, 0xb7, 0xa4, 0x4f, 0xfe, 0xc8, 0xe9, 0x17, 0x37, 0xf3, 0x30, 0x92,
	0xbb, 0x19, 0xfa, 0x37, 0x3f, 0xf1, 0x97, 0xba, 0x90, 0x3d, 0xf2, 0xfc, 0x7f, 0xb4, 0xa4, 0x3f,
	0x10, 0x3b, 0xbf, 0xe4, 0x7e, 0x7b, 0xf6, 0xb2, 0xb1, 0x02, 0x53, 0x46, 0x7d, 0xc9, 0x6d, 0x32,
	0x0b, 0x15, 0xa7, 0xac, 0xf3, 0x37, 0x15, 0x55, 0x3d, 0xf9, 0x7a, 0x0d, 0x56, 0x61, 0x72, 0x07,
	0xa9, 0x40, 0x41, 0xe6, 0x8a, 0x79, 0xa7, 0x42, 0x7b, 0xea, 0x88, 0x0b, 0x76, 0xae, 0xbf, 0x15,
	0xd7, 0xf3, 0xad, 0x69, 0x80, 0x14, 0xf0, 0xde, 0xeb, 0x47, 0x1d, 0xa6, 0x8e, 0x7a, 0xad, 0x5a,
	0x9b, 0x77, 0xeb, 0xc7, 0xbd, 0x16, 0x1e, 0x06, 0xfc, 0x74, 0xa0, 0xbe, 0xc1, 0x2f, 0xd3, 0x0e,
	0xf7, 0xda, 0x01, 0xc3, 0x50, 0xb5, 0x26, 0xf5, 0x05, 0x7a, 0xf4, 0x5f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xf3, 0x04, 0x1d, 0x1c, 0x53, 0x0b, 0x00, 0x00,
}
