apiVersion: v1
kind: Service
metadata:
  labels:
    application-crd-id: kubeflow-pipelines
    app: ml-pipeline-ui
  name: ml-pipeline-ui
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: ml-pipeline-ui