apiVersion: v1
kind: Service
metadata:
  name: ml-pipeline-visualizationserver
  labels:
    application-crd-id: kubeflow-pipelines
spec:
  ports:
  - name: http
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: ml-pipeline-visualizationserver