apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    application-crd-id: kubeflow-pipelines
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
