apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: application-manager-role
  labels:
    application-crd-id: kubeflow-pipelines
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - get
      - list
      - update
      - patch
      - watch
  - apiGroups:
      - app.k8s.io
    resources:
      - '*'
    verbs:
      - '*'