apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Identifier for application manager to apply ownerReference.
# The ownerReference ensures the resources get garbage collected
# when application is deleted.
commonLabels:
  application-crd-id: kubeflow-pipelines

resources:
- minio-gcs-gateway-deployment.yaml
- minio-gcs-gateway-service.yaml