apiVersion: v1
kind: Service
metadata:
  name: minio-service
  labels:
    application-crd-id: kubeflow-pipelines
spec:
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: minio