applicationApiVersion: v1beta1

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  image.mysql:
    type: string
    default: $REGISTRY/mysql:5.6
    x-google-marketplace:
      type: IMAGE

  IMAGE_AIRFLOWOPERATOR:
    type: string
    default: $REGISTRY:$TAG
    x-google-marketplace:
      type: IMAGE

required:
  - name
  - namespace