apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Identifier for application manager to apply ownerReference.
# The ownerReference ensures the resources get garbage collected
# when application is deleted.
commonLabels:
  application-crd-id: kubeflow-pipelines

resources:
  - metadata-configmap.yaml
  - metadata-mysql-secret.yaml
  - metadata-deployment.yaml
  - metadata-service.yaml
  - metadata-envoy-deployment.yaml
  - metadata-envoy-service.yaml
