kind: Service
apiVersion: v1
metadata:
  labels:
    application-crd-id: kubeflow-pipelines
    app: metadata
  name: metadata-envoy-service
spec:
  selector:
    component: metadata-envoy
  type: ClusterIP
  ports:
  - port: 9090
    protocol: TCP
    name: md-envoy
