apiVersion: v1
kind: ConfigMap
metadata:
  name: metadata-configmap
  labels:
    application-crd-id: kubeflow-pipelines
    component: metadata-server
data:
  mysql_database: "metadb"
  mysql_host: "mysql"
  mysql_port: "3306"
