apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

resources:
- namespace.yaml

namespace: kubeflow

patchesStrategicMerge:
- ../namespaced/workflow-controller-configmap.yaml
- ../namespaced/ml-pipeline-persistenceagent-deployment-patch.yaml
- ../namespaced/ml-pipeline-scheduledworkflow-deployment-patch.yaml
- ../namespaced/ml-pipeline-viewer-crd-deployment-patch.yaml
- ../namespaced/ml-pipeline-ui-deployment-patch.yaml

vars:
  - name: NAMESPACE
    objref:
      kind: Deployment
      apiVersion: apps/v1beta2
      name:  workflow-controller
    fieldref:
      fieldpath: metadata.namespace

configurations:
- ../namespaced/kustomizeconfig/namespace.yaml
