apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../namespaced
  - minio
  - mysql

# Replace with your namespace
namespace: kubeflow2

images:
  - name: gcr.io/cloudsql-docker/gce-proxy
    newTag: "1.14"
  - name: minio/minio
    newTag: RELEASE.2019-08-14T20-37-41Z