apiVersion: v1
kind: Service
metadata:
  name: minio-service
  labels:
    application-crd-id: kubeflow-pipelines
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: minio